### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by themattinthehatt** [paninski-lab/deepgraphpose#3]
https://github.com/paninski-lab/deepgraphpose/blob/0c5d91b8ef76d04a1438cfb4c7c391fc584d4f84/src/deepgraphpose/models/eval.py#L339

when running DGP on a large video this line gives me an out of memory error (required ~40GB of memory). Since this variable is only used in one other place (L348) I would suggest removing L339 and replacing L348 with:

```
sigmoid_pred_np_jj = np.exp(softmaxtensors [ff_idx, :, :, jj_idx]) / (np.exp(softmaxtensors [ff_idx, :, :, jj_idx]) + 1)
```

**Comment by themattinthehatt** [comment]
the previous out of memory error arose from a video that was very long (~500K time points); I now have a similar issue with a video that is very large (~1K x 1K), where allocating `softmaxtensors` itself takes too much memory. I would suggest updating the eval function to not unnecessarily allocate this variable, perhaps as so:

```
markers = np.zeros((n_frames + 1, dlc_cfg.num_joints, 2))

mu_likelihoods = np.zeros((n_frames, nj, 2)).astype('int')
likelihoods = np.zeros((n_frames + 1, nj))
offset_mu_jj = 0

pbar = tqdm(total=n_frames, desc='processing video frames')
for ii, frame in enumerate(video_clip.iter_frames()):
  frame = Image.fromarray(frame)
  if new_size is not None:
      scale_x = frame.width / new_size[1]
      scale_y = frame.height / new_size[0]
      # width, height
      frame = frame.resize(size=(new_size[1], new_size[0]))
  else:
      scale_x = 1
      scale_y = 1
  if crop_size is not None:
      # crop
      frame = frame.crop(crop_size)
      xmin = crop_size[0]
      ymin = crop_size[1]
  else:
      xmin = 0
      ymin = 0

  frame = np.asarray(frame)
  ff = img_as_ubyte(frame)

  mu_n_batch, scmap_np = sess.run([mu_n, scmap], feed_dict={inputs: ff[None, :, :, :]})
  markers[ii] = mu_n_batch[0]
  softmaxtensor = scmap_np[0]
  for jj_idx in range(nj):
      mu_jj = markers[ii, jj_idx]
      ends_floor = np.floor(mu_jj).astype('int') - offset_mu_jj
      ends_ceil = np.ceil(mu_jj).astype('int') + 1 + offset_mu_jj
      # sigmoid_pred_np_jj = sigmoid_pred_np[ff_idx, :, :, jj_idx]
      sigmoid_pred_np_jj = np.exp(softmaxtensor[:, :, jj_idx]) / \
                           (np.exp(softmaxtensor[:, :, jj_idx]) + 1)
      spred_centered = sigmoid_pred_np_jj[
                       ends_floor[0]:ends_ceil[0], ends_floor[1]:ends_ceil[1]]
      mu_likelihoods[ii, jj_idx] = np.unravel_index(np.argmax(spred_centered),
                                                        spred_centered.shape)
      mu_likelihoods[ii, jj_idx] += [ends_floor[0], ends_floor[1]]
      likelihoods[ii, jj_idx] = sigmoid_pred_np_jj[
          int(mu_likelihoods[ii, jj_idx][0]), int(mu_likelihoods[ii, jj_idx][1])]

  pbar.update(1)
```

**Comment by obarnstedt** [comment]
Hi,
thanks for that suggestion, @themattinthehatt ! I've run into the same memory error problem on the softmaxtensors allocation with a 800x600x400k video (n_frames=359020, ny_out=78, nx_out=103, nj=15). Your code suggestion solved the problem, but three small issues here that needed fixing:
1. In the existing code, the reference is to 'softmaxtensors' with an 's' in the end.
2. 'crop_size' does not seem to be defined within the function.
3. 'likelihoods = np.zeros((n_frames + 1, nj))' -- not sure why the first dimension would be n_frames+1 and not n_frames. If I run this with n_frames+1 I receive an error that it's trying to assign too many values to the labels.

**Comment by waq1129** [comment]
Hi

Thank you so much for finding this memory issue and proposing these solutions. They are all fixed and updated. 

Best.
